# Generated by Django 4.0.5 on 2022-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_alter_inputform_dataform_alter_selectform_dataform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectform',
            name='choices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
