# Generated by Django 4.0.5 on 2022-06-22 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_alter_selectform_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataform',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
