# Generated by Django 4.0.5 on 2022-06-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_dataform_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputform',
            old_name='dataForm',
            new_name='data_form',
        ),
        migrations.RenameField(
            model_name='inputform',
            old_name='data',
            new_name='data_input',
        ),
        migrations.RenameField(
            model_name='selectform',
            old_name='dataForm',
            new_name='data_form',
        ),
        migrations.RenameField(
            model_name='textareaform',
            old_name='dataForm',
            new_name='data_form',
        ),
        migrations.RenameField(
            model_name='textareaform',
            old_name='data',
            new_name='data_textarea',
        ),
    ]
