# Generated by Django 4.0.5 on 2022-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_rename_dataform_dataformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectform',
            name='select',
            field=models.CharField(blank=True, max_length=200, verbose_name='select'),
        ),
    ]
