# Generated by Django 4.0.5 on 2022-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0008_dataformmodel_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputform',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='selectform',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='textareaform',
            name='description',
            field=models.CharField(blank=True, max_length=1500, verbose_name='description'),
        ),
    ]
