# Generated by Django 4.0.5 on 2022-07-04 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDataForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='SiteTextareaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('data_textarea', models.TextField(verbose_name='textarea')),
                ('data_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textarea_forms', to='app_site.sitedataform')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSelectForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('choices', models.JSONField(blank=True, default=dict, null=True)),
                ('data_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_forms', to='app_site.sitedataform')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInputForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('data_input', models.CharField(max_length=200, verbose_name='input')),
                ('data_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_forms', to='app_site.sitedataform')),
            ],
        ),
    ]
