# Generated by Django 4.0.5 on 2022-07-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinputform',
            name='data_form',
        ),
        migrations.RemoveField(
            model_name='siteselectform',
            name='data_form',
        ),
        migrations.RemoveField(
            model_name='sitetextareaform',
            name='data_form',
        ),
        migrations.DeleteModel(
            name='SiteDataForm',
        ),
        migrations.DeleteModel(
            name='SiteInputForm',
        ),
        migrations.DeleteModel(
            name='SiteSelectForm',
        ),
        migrations.DeleteModel(
            name='SiteTextareaForm',
        ),
    ]
